-- 0006_arp_replace_sources_v2.sql
-- Replace ARP sources from the canonical research.csv export (correct column mapping).
-- One-off corrective migration: deletes sources+evidence for activities present in the CSV, then re-inserts.
-- Activity IDs are mapped by activity_name to avoid ID mismatches across environments.

CREATE SCHEMA IF NOT EXISTS "__ARP_SCHEMA__";

WITH data(source_id, activity_name, title, organization, jurisdiction, url, source_type, activities_covered_raw, brief_focus, authority_class, publication_date) AS (
  VALUES
  ('stand-up-paddleboarding-sup-paddle-uk-paddlesafer-pdf-https-paddleuk-org-uk-w-6d4adc9950d4', 'Stand-up paddleboarding (SUP)', 'Paddlesafer (PDF)', 'Paddle UK', 'United Kingdom', 'https://paddleuk.org.uk/wp-content/uploads/2025/04/Paddlesafer-V8-2025.pdf', 'Governing Body', 'Paddlesport (incl. SUP, kayaking, canoeing)', 'Safety guidance for paddlesport across environments; planning, equipment, incident response, and environment definitions.', '', ''),
  ('stand-up-paddleboarding-sup-paddle-australia-safety-guidelines-v2-https-paddl-aab822ca4a7f', 'Stand-up paddleboarding (SUP)', 'Safety Guidelines v2', 'Paddle Australia', 'Australia', 'https://paddle.org.au/education/safety-guidelines-v2/', 'Governing Body', 'Recreational paddling (incl. SUP)', 'Minimum safety requirements for recreational paddling; planning, people, equipment, and incident reporting.', '', ''),
  ('stand-up-paddleboarding-sup-maritime-new-zealand-paddle-craft-https-www-marit-659e5e0e20d6', 'Stand-up paddleboarding (SUP)', 'Paddle craft', 'Maritime New Zealand', 'New Zealand', 'https://www.maritimenz.govt.nz/recreational/paddle-craft/', 'Government', 'Paddle craft (incl. kayaks/canoes and similar human-powered craft)', 'Government safety information and downloadable guidance for recreational paddle craft; visibility, lifejackets, and preparation.', '', ''),
  ('stand-up-paddleboarding-sup-transport-canada-operating-a-human-powered-craft--147957b0af35', 'Stand-up paddleboarding (SUP)', 'Operating a human-powered craft', 'Transport Canada', 'Canada', 'https://tc.canada.ca/en/marine-transportation/preparing-operate-your-vessel/operating-human-powered-craft', 'Government', 'Human-powered craft (incl. paddleboards)', 'Safety tips and regulatory requirements for paddleboards and other human-powered vessels.', '', ''),
  ('stand-up-paddleboarding-sup-royal-national-lifeboat-institution-rnli-stand-up-53230dee1778', 'Stand-up paddleboarding (SUP)', 'Stand-up paddleboarding: safety advice', 'Royal National Lifeboat Institution (RNLI)', 'United Kingdom / Ireland', 'https://rnli.org/safety/choose-your-activity/stand-up-paddleboarding', 'NGO', 'Stand-up paddleboarding', 'Coastal and nearshore SUP safety considerations, including conditions and emergency actions.', '', ''),
  ('stand-up-paddleboarding-sup-department-of-transport-western-australia-safety--a28258424c68', 'Stand-up paddleboarding (SUP)', 'Safety Guidelines – Paddle Craft (brochure PDF)', 'Department of Transport, Western Australia', 'Australia (Western Australia)', 'https://www.transport.wa.gov.au/getmedia/37417389-93f2-46c2-8555-01526e5adf79/mac-b-paddlesafe.pdf', 'Government', 'Paddle craft (incl. SUP)', 'Planning and equipment guidance for safe paddling; visibility, rules, and carrying required safety gear.', '', ''),
  ('stand-up-paddleboarding-sup-australian-adventure-activity-standards-aaas-inla-c07d3f98b86e', 'Stand-up paddleboarding (SUP)', 'Inland Water Paddling – Good Practice Guide', 'Australian Adventure Activity Standards (AAAS)', 'Australia', 'https://www.aaas.org.au/guidance/inland-water-paddling/', 'NGO', 'Inland water paddling (incl. SUP and paddlecraft)', 'Good-practice guide for planning and running inland water paddling activities; hazards, leadership, and context factors.', '', ''),
  ('stand-up-paddleboarding-sup-american-canoe-association-aca-the-paddler-s-safe-2beb39011fc1', 'Stand-up paddleboarding (SUP)', 'The Paddler’s Safety Checklist (PDF)', 'American Canoe Association (ACA)', 'United States', 'https://americancanoe.org/wp-content/uploads/documents/sei-educational_resources/paddlers_safety_checklist.pdf', 'NGO', 'Canoeing, kayaking, SUP, rafting', 'Checklist-style resource for trip planning, equipment, group preparedness, and risk awareness for paddlers.', '', ''),
  ('surfing-beginner-instruction-queensland-department-of-education-surfing-cara--3ad746a988f6', 'Surfing – beginner instruction', 'Surfing (CARA Activity Guideline)', 'Queensland Department of Education', 'Australia (Queensland)', 'https://education.qld.gov.au/curriculum/stages-of-schooling/CARA/activity-guidelines/surfing', 'Education', 'Surfing (incl. bodyboarding in surf context)', 'School activity guideline covering hazards, supervision ratios/competence, site selection, and environmental dependencies.', '', ''),
  ('surfing-beginner-instruction-royal-national-lifeboat-institution-rnli-surfing-75ccaaea6f08', 'Surfing – beginner instruction', 'Surfing: safety advice', 'Royal National Lifeboat Institution (RNLI)', 'United Kingdom / Ireland', 'https://rnli.org/safety/choose-your-activity/surfing', 'NGO', 'Surfing', 'Surf-specific safety advice including conditions, surf etiquette, and cautions about environment and ability limits.', '', ''),
  ('surfing-beginner-instruction-surf-life-saving-australia-beach-safety-flags-si-2ffc7f8e2a41', 'Surfing – beginner instruction', 'Beach Safety – Flags & Signs (Fact Sheet PDF)', 'Surf Life Saving Australia', 'Australia', 'https://nanoslsa.blob.core.windows.net/beachsafe/media/article/13/Flags_and_Signs_Fact_SheetA4_SLSA_2020.pdf', 'NGO', 'Beach activities (incl. surfing)', 'Explains beach flag/sign systems used to communicate hazards and designated activity areas.', '', ''),
  ('surfing-beginner-instruction-international-life-saving-federation-ilsf-beach--b4d001a87c56', 'Surfing – beginner instruction', 'Beach Flags & Signs Standard: LPS 14 (PDF)', 'International Life Saving Federation (ILSF)', 'International', 'https://www.ilsf.org/sites/ilsf.org/files/filefield_paths/LPS14_0.pdf', 'Governing Body', 'Beach safety signage for aquatic activities', 'International standard describing beach safety flags and signs used to indicate hazards and zones.', '', ''),
  ('surfing-beginner-instruction-national-oceanic-and-atmospheric-administration--350eabedadc8', 'Surfing – beginner instruction', 'Rip Current Safety', 'National Oceanic and Atmospheric Administration (NOAA)', 'United States', 'https://www.noaa.gov/jetstream/ocean/rip-currents/rip-current-safety', 'Government', 'Beach and surf water activities', 'Rip current characteristics and safety actions; emphasizes environmental conditions and limitations.', '', ''),
  ('surfing-beginner-instruction-u-s-national-weather-service-nws-rip-current-saf-636b1dd6f36b', 'Surfing – beginner instruction', 'Rip Current Safety', 'U.S. National Weather Service (NWS)', 'United States', 'https://www.weather.gov/safety/ripcurrent', 'Government', 'Beach and surf water activities', 'Public safety guidance on rip currents and other beach hazards; links to additional safety information.', '', ''),
  ('surfing-beginner-instruction-met-office-10-beach-safety-tips-https-weather-me-b5d4aab1e55f', 'Surfing – beginner instruction', '10 beach safety tips', 'Met Office', 'United Kingdom', 'https://weather.metoffice.gov.uk/warnings-and-advice/seasonal-advice/travel/out-and-about/10-beach-safety-tips', 'Government', 'Beach visits (incl. surf activities)', 'Weather- and conditions-aware beach safety messaging, including rip currents and use of lifeguarded beaches.', '', ''),
  ('surfing-beginner-instruction-hm-coastguard-coast-coastal-safety-information-h-15389fca4dc5', 'Surfing – beginner instruction', 'Coast: coastal safety information', 'HM Coastguard', 'United Kingdom', 'https://hmcoastguard.uk/coast', 'Government', 'Coastal activities (general)', 'Coastal hazard awareness and emergency actions for people visiting or recreating at the coast.', '', ''),
  ('bodyboarding-queensland-department-of-education-surfing-cara-activity-guideli-0fea927f8821', 'Bodyboarding', 'Surfing (CARA Activity Guideline)', 'Queensland Department of Education', 'Australia (Queensland)', 'https://education.qld.gov.au/curriculum/stages-of-schooling/CARA/activity-guidelines/surfing', 'Education', 'Surfing (incl. bodyboarding in surf context)', 'School activity guideline covering hazards, supervision ratios/competence, site selection, and environmental dependencies.', '', ''),
  ('bodyboarding-royal-national-lifeboat-institution-rnli-bodyboarding-safety-adv-8f3740aaf48c', 'Bodyboarding', 'Bodyboarding: safety advice', 'Royal National Lifeboat Institution (RNLI)', 'United Kingdom / Ireland', 'https://rnli.org/safety/choose-your-activity/bodyboarding', 'NGO', 'Bodyboarding', 'Bodyboarding-specific safety advice focusing on surf conditions, ability limits, and emergency actions.', '', ''),
  ('bodyboarding-surf-life-saving-australia-beach-safety-flags-signs-fact-sheet-p-b9ff74113711', 'Bodyboarding', 'Beach Safety – Flags & Signs (Fact Sheet PDF)', 'Surf Life Saving Australia', 'Australia', 'https://nanoslsa.blob.core.windows.net/beachsafe/media/article/13/Flags_and_Signs_Fact_SheetA4_SLSA_2020.pdf', 'NGO', 'Beach activities (incl. bodyboarding)', 'Explains beach flag/sign systems used to communicate hazards and designated activity areas.', '', ''),
  ('bodyboarding-international-life-saving-federation-ilsf-beach-flags-signs-stan-78134ae5ad00', 'Bodyboarding', 'Beach Flags & Signs Standard: LPS 14 (PDF)', 'International Life Saving Federation (ILSF)', 'International', 'https://www.ilsf.org/sites/ilsf.org/files/filefield_paths/LPS14_0.pdf', 'Governing Body', 'Beach safety signage for aquatic activities', 'International standard describing beach safety flags and signs used to indicate hazards and zones.', '', ''),
  ('bodyboarding-national-oceanic-and-atmospheric-administration-noaa-rip-current-8c2ca7f3beab', 'Bodyboarding', 'Rip Current Safety', 'National Oceanic and Atmospheric Administration (NOAA)', 'United States', 'https://www.noaa.gov/jetstream/ocean/rip-currents/rip-current-safety', 'Government', 'Beach and surf water activities', 'Rip current characteristics and safety actions; emphasizes environmental conditions and limitations.', '', ''),
  ('bodyboarding-u-s-national-weather-service-nws-rip-current-safety-https-www-we-fadf7548beb9', 'Bodyboarding', 'Rip Current Safety', 'U.S. National Weather Service (NWS)', 'United States', 'https://www.weather.gov/safety/ripcurrent', 'Government', 'Beach and surf water activities', 'Public safety guidance on rip currents and other beach hazards; links to additional safety information.', '', ''),
  ('bodyboarding-met-office-understanding-rip-currents-https-weather-metoffice-go-c3e6a91e0150', 'Bodyboarding', 'Understanding rip currents', 'Met Office', 'United Kingdom', 'https://weather.metoffice.gov.uk/warnings-and-advice/seasonal-advice/travel/out-and-about/understanding-rip-currents', 'Government', 'Beach and surf water activities', 'Explains rip current formation and how conditions affect risk; emphasizes cautions about sea state.', '', ''),
  ('bodyboarding-surf-life-saving-queensland-flags-signs-https-lifesaving-com-au--47e960d09c7b', 'Bodyboarding', 'Flags & Signs', 'Surf Life Saving Queensland', 'Australia (Queensland)', 'https://lifesaving.com.au/safety-info/flags-signs', 'NGO', 'Beach activities (incl. bodyboarding)', 'Queensland-focused beach flag/sign explanations and safety cautions for surf conditions.', '', ''),
  ('scuba-discover-experiences-queensland-department-of-education-scuba-diving-ca-b2ce3cd2bf2d', 'Scuba “discover” experiences', 'Scuba diving (CARA Activity Guideline)', 'Queensland Department of Education', 'Australia (Queensland)', 'https://education.qld.gov.au/curriculum/stages-of-schooling/CARA/activity-guidelines/scuba-diving', 'Education', 'Scuba diving (school activities)', 'School activity guideline outlining hazards, supervision/competency expectations, and environmental considerations.', '', ''),
  ('scuba-discover-experiences-worksafe-queensland-recreational-diving-recreation-48f196185e98', 'Scuba “discover” experiences', 'Recreational Diving, Recreational Technical Diving and Snorkelling Code of Practice 2024 (PDF)', 'WorkSafe Queensland', 'Australia (Queensland)', 'https://www.worksafe.qld.gov.au/__data/assets/pdf_file/0023/41387/recreational-diving-recreational-technical-diving-and-snorkelling-code-of-practice-2024.pdf', 'Government', 'Recreational diving and snorkelling operations', 'Government code of practice describing risk management expectations, supervision, and operational controls for recreational diving.', '', ''),
  ('scuba-discover-experiences-worksafe-queensland-diving-snorkelling-and-recreat-83ff826fda7b', 'Scuba “discover” experiences', 'Diving, snorkelling and recreational water activities laws', 'WorkSafe Queensland', 'Australia (Queensland)', 'https://www.worksafe.qld.gov.au/your-industry/diving-and-snorkelling/diving-laws', 'Government', 'Diving/snorkelling legal and regulatory framework', 'Overview of relevant Acts, regulations, and codes of practice applicable to diving and snorkelling activities.', '', ''),
  ('scuba-discover-experiences-worksafe-queensland-diving-snorkelling-and-recreat-c02c513bf5e3', 'Scuba “discover” experiences', 'Diving, snorkelling and recreational water activities resources', 'WorkSafe Queensland', 'Australia (Queensland)', 'https://www.worksafe.qld.gov.au/your-industry/diving-and-snorkelling/diving-snorkelling-and-recreational-water-activities-resources', 'Government', 'Diving and snorkelling resources (incl. non-certified diver supervision)', 'Central resource hub including operator guides and materials on supervision of non-certified divers and other cautions.', '', ''),
  ('scuba-discover-experiences-health-and-safety-executive-hse-diving-guidance-po-674ecf38a051', 'Scuba “discover” experiences', 'Diving (guidance portal)', 'Health and Safety Executive (HSE)', 'United Kingdom', 'https://www.hse.gov.uk/diving/', 'Government', 'Diving (incl. recreational instruction and work diving)', 'Government guidance covering diving risk management, including areas that mention recreational instruction.', '', ''),
  ('scuba-discover-experiences-health-and-safety-executive-hse-recreational-divin-666f5846de06', 'Scuba “discover” experiences', 'Recreational diving projects (Approved Code of Practice and guidance: L105)', 'Health and Safety Executive (HSE)', 'United Kingdom', 'https://www.hse.gov.uk/pubns/books/l105.htm', 'Government', 'Recreational diving projects under UK regulations', 'Approved code of practice setting out requirements and cautions for recreational diving projects within scope of regulations.', '', ''),
  ('scuba-discover-experiences-divers-alert-network-dan-diving-medical-guidance-t-e06052618f71', 'Scuba “discover” experiences', 'Diving Medical Guidance to the Physician (PDF)', 'Divers Alert Network (DAN)', 'International (NGO)', 'https://dan.org/wp-content/uploads/2021/03/diving_medical_guidance_2021-01-29.pdf', 'NGO', 'Recreational scuba diving medical screening considerations', 'Medical guidance describing health considerations and limitations relevant to fitness for diving.', '', ''),
  ('scuba-discover-experiences-british-sub-aqua-club-bsac-safe-diving-guide-pdf-h-7be7069f0bd9', 'Scuba “discover” experiences', 'Safe Diving Guide (PDF)', 'British Sub-Aqua Club (BSAC)', 'United Kingdom', 'https://www.bsac.com/wp-content/uploads/2017/02/BSAC_Safe-Diving_Guide.pdf', 'NGO', 'Recreational scuba diving', 'Safety guide addressing common risks, planning, and cautions for club and recreational divers.', '', ''),
  ('free-diving-breath-hold-snorkeling-international-life-saving-federation-ilsf--e899424e2037', 'Free diving / breath-hold snorkeling', 'Medical Position Statement MPS-16: Shallow water black-out (PDF)', 'International Life Saving Federation (ILSF)', 'International', 'https://www.ilsf.org/sites/ilsf.org/files/Position%20Statements/Medical%20Position%20Statements/MPS-16%202011%20Shallow%20water%20black-out.pdf', 'Governing Body', 'Breath-hold diving/apnoea and related aquatic activities', 'Medical position statement describing shallow-water blackout risk factors and cautions related to breath-hold activity.', '', ''),
  ('free-diving-breath-hold-snorkeling-centers-for-disease-control-and-prevention-486427b3811a', 'Free diving / breath-hold snorkeling', 'Hypoxic Blackout and Drowning Associated with Underwater Breath-Holding Behavior — New York, 1988–2011', 'Centers for Disease Control and Prevention (CDC)', 'United States', 'https://www.cdc.gov/mmwr/preview/mmwrhtml/mm6306a4.htm', 'Government', 'Underwater breath-holding (apnoea) risks', 'Epidemiological report highlighting breath-holding behaviors, risk characteristics, and supervision implications.', '', ''),
  ('free-diving-breath-hold-snorkeling-royal-life-saving-society-uk-rlss-uk-shall-e3d473950a19', 'Free diving / breath-hold snorkeling', 'Shallow Water Blackout, Hyperventilation, and Breath Holding (GS005)', 'Royal Life Saving Society UK (RLSS UK)', 'United Kingdom', 'https://www.rlss.org.uk/shallow-water-blackout-hyperventilation-and-breath-holding-gs005', 'NGO', 'Breath-hold swimming/diving', 'Public guidance statement describing SWB risk characteristics, cautions, and supervision considerations.', '', ''),
  ('free-diving-breath-hold-snorkeling-royal-life-saving-society-australia-hypoxi-9cb41af8778f', 'Free diving / breath-hold snorkeling', 'Hypoxic Blackout (information page)', 'Royal Life Saving Society – Australia', 'Australia', 'https://www.royallifesaving.com.au/stay-safe-active/locations/pool/hypoxic-blackout', 'NGO', 'Breath-hold activity in pools/open water', 'Explains hypoxic blackout hazards and cautions associated with breath-hold practices.', '', ''),
  ('free-diving-breath-hold-snorkeling-american-red-cross-what-is-hypoxic-blackou-611cc5e34720', 'Free diving / breath-hold snorkeling', 'What is Hypoxic Blackout?', 'American Red Cross', 'United States', 'https://www.redcross.org/take-a-class/resources/articles/what-is-hypoxic-blackout', 'NGO', 'Breath-hold swimming/diving', 'Explains hypoxic blackout risk and supervision considerations for underwater breath-holding.', '', ''),
  ('free-diving-breath-hold-snorkeling-usa-swimming-underwater-breath-control-and-ebb85b99816c', 'Free diving / breath-hold snorkeling', 'Underwater Breath Control and Hypoxic Training (presentation PDF)', 'USA Swimming', 'United States', 'https://www.usaswimming.org/docs/default-source/safe-sport/breath-control_presentation.pdf', 'Governing Body', 'Aquatic sports training (breath control)', 'Presentation material describing risks and cautions associated with breath control/hypoxic practices.', '', ''),
  ('free-diving-breath-hold-snorkeling-divers-alert-network-dan-shallow-water-bla-bb586df84e5e', 'Free diving / breath-hold snorkeling', 'Shallow-Water Blackout (article)', 'Divers Alert Network (DAN)', 'International (NGO)', 'https://dan.org/alert-diver/article/shallow-water-blackout/', 'NGO', 'Freediving/apnoea and breath-hold activities', 'Article describing SWB risk mechanisms, contributing factors, and supervision limitations.', '', ''),
  ('free-diving-breath-hold-snorkeling-naval-safety-command-u-s-navy-lessons-lear-199909bed1e9', 'Free diving / breath-hold snorkeling', 'Lessons Learned LL 20-19: Shallow Water Blackout (PDF)', 'Naval Safety Command (U.S. Navy)', 'United States', 'https://navalsafetycommand.navy.mil/Portals/100/LL%2020-19%20Shallow%20Water%20Blackout.pdf', 'Government', 'Breath-hold diving/freediving', 'Incident-focused lessons learned describing SWB hazard mechanisms and prevention cautions.', '', ''),
  ('rowing-instructional-queensland-department-of-education-rowing-cara-activity--3ce42fa9adfa', 'Rowing – instructional', 'Rowing (CARA Activity Guideline)', 'Queensland Department of Education', 'Australia (Queensland)', 'https://education.qld.gov.au/curriculum/stages-of-schooling/CARA/activity-guidelines/rowing', 'Education', 'Rowing (school activities)', 'School activity guideline addressing hazards, supervision/competency, equipment checks, and environmental factors.', '', ''),
  ('rowing-instructional-british-rowing-rowsafe-british-rowing-safety-guidance-ht-39ed246c1f1d', 'Rowing – instructional', 'RowSafe (British Rowing safety guidance)', 'British Rowing', 'United Kingdom', 'https://www.britishrowing.org/about-us/policies-guidance/rowsafe/', 'Governing Body', 'Rowing', 'National governing body safety guidance for rowing clubs and sessions; covers conditions, equipment, and supervision.', '', ''),
  ('rowing-instructional-rowing-australia-on-water-safety-guidelines-pdf-https-ro-3f3cfd236736', 'Rowing – instructional', 'On-Water Safety Guidelines (PDF)', 'Rowing Australia', 'Australia', 'https://rowingaustralia.com.au/wp-content/uploads/2020/11/Rowing_Australia_On-Water_Safety_Guidelines.pdf', 'Governing Body', 'Rowing', 'Rowing-specific safety guidance addressing boating environments, crew competency, and operational controls.', '', ''),
  ('rowing-instructional-usrowing-safety-resources-https-usrowing-org-about-safet-e668479470ef', 'Rowing – instructional', 'Safety Resources', 'USRowing', 'United States', 'https://usrowing.org/about-safety/safety-resources', 'Governing Body', 'Rowing', 'Safety resources hub including downloadable safety guidelines and audit checklists for rowing programs.', '', ''),
  ('rowing-instructional-rowing-canada-aviron-rowing-canada-aviron-safety-guideli-c15ce55079b5', 'Rowing – instructional', 'Rowing Canada Aviron Safety Guidelines (PDF)', 'Rowing Canada Aviron', 'Canada', 'https://rowingcanada.org/uploads/2019/05/safetyguidelinesrcav2.pdf', 'Governing Body', 'Rowing', 'Rowing safety requirements referencing boating regulations, equipment, and procedural controls.', '', ''),
  ('rowing-instructional-world-rowing-fisa-fisa-s-minimum-guidelines-for-the-safe-de371f68546b', 'Rowing – instructional', 'FISA’s Minimum Guidelines for the Safe Practice of Rowing (PDF)', 'World Rowing (FISA)', 'International', 'https://worldrowing.com/wp-content/uploads/2020/12/FISA%E2%80%99sMinimumGuidelinesfortheSafePracticeofRowing_Neutral.pdf', 'Governing Body', 'Rowing (training/practice)', 'Minimum safety guidelines emphasizing weather/water conditions, time of day, equipment, and supervision.', '', ''),
  ('rowing-instructional-rowing-new-zealand-water-safety-code-2016-pdf-https-rowi-232d2fbd383f', 'Rowing – instructional', 'Water Safety Code 2016 (PDF)', 'Rowing New Zealand', 'New Zealand', 'https://rowingnz.kiwi/wp-content/uploads/2024/11/Water-Safety-Code-2016.pdf', 'Governing Body', 'Rowing', 'Rowing safety code detailing responsibilities, oversight roles, and operational minimum standards.', '', ''),
  ('rowing-instructional-transport-canada-safe-boating-guide-safety-tips-and-requ-fed01462f739', 'Rowing – instructional', 'Safe Boating Guide – Safety Tips and Requirements for Pleasure Crafts (PDF)', 'Transport Canada', 'Canada', 'https://tc.canada.ca/sites/default/files/2024-05/Safe%20Boating%20Guide%20%E2%80%93%20Safety%20Tips%20and%20Requirements%20for%20Pleasure%20Crafts%20-%20tp_511e.pdf', 'Government', 'Small craft/boating (incl. rowing craft contexts)', 'Boating safety and regulatory requirements relevant to operating small craft on waterways.', '', ''),
  ('water-polo-aquatic-sports-queensland-department-of-education-water-polo-cara--e1218ee820dc', 'Water polo / aquatic sports', 'Water polo (CARA Activity Guideline)', 'Queensland Department of Education', 'Australia (Queensland)', 'https://education.qld.gov.au/curriculum/stages-of-schooling/CARA/activity-guidelines/water-polo', 'Education', 'Water polo (school activities)', 'School activity guideline covering hazards, supervision, facility requirements, and participant capability considerations.', '', ''),
  ('water-polo-aquatic-sports-world-aquatics-water-polo-rules-https-www-worldaqua-aeef853be878', 'Water polo / aquatic sports', 'Water Polo Rules', 'World Aquatics', 'International', 'https://www.worldaquatics.com/rules/water-polo', 'Governing Body', 'Water polo (rules framework)', 'Official rule framework for water polo, including definitions, conduct, and match environment requirements.', '', ''),
  ('water-polo-aquatic-sports-usa-water-polo-safety-policies-https-usawaterpolo-o-4de60e87f3d9', 'Water polo / aquatic sports', 'Safety Policies', 'USA Water Polo', 'United States', 'https://usawaterpolo.org/sports/2018/12/19/safety-policies.aspx', 'Governing Body', 'Water polo (youth and competitive contexts)', 'Policies addressing athlete safety and misconduct prevention, including MAAP-related safeguards.', '', ''),
  ('water-polo-aquatic-sports-usa-water-polo-health-and-safety-https-usawaterpolo-3bbbf515e561', 'Water polo / aquatic sports', 'Health and Safety', 'USA Water Polo', 'United States', 'https://usawaterpolo.org/sports/2021/1/20/health-safety.aspx', 'Governing Body', 'Water polo (membership programs)', 'Health and safety information for members, including training expectations and reporting pathways.', '', ''),
  ('water-polo-aquatic-sports-water-polo-australia-policies-procedures-by-laws-po-35de49c7e41a', 'Water polo / aquatic sports', 'Policies & Procedures (By-Laws, Policies and Procedures hub)', 'Water Polo Australia', 'Australia', 'https://www.waterpoloaustralia.com.au/info-hub/policies-procedures', 'Governing Body', 'Water polo (national sport governance)', 'Central hub for organizational policies and procedures relevant to managing the sport safely.', '', ''),
  ('water-polo-aquatic-sports-water-polo-australia-risk-management-club-governanc-3f7c04781e46', 'Water polo / aquatic sports', 'Risk Management (club governance guidance)', 'Water Polo Australia', 'Australia', 'https://www.waterpoloaustralia.com.au/club-pool/governance-risk-management', 'Governing Body', 'Water polo (club operations)', 'Risk management guidance for clubs, including identification and mitigation of operational risks.', '', ''),
  ('water-polo-aquatic-sports-centers-for-disease-control-and-prevention-cdc-2023-4718e8a191f0', 'Water polo / aquatic sports', '2023 Model Aquatic Health Code (MAHC), 4th Edition – Code Language (PDF)', 'Centers for Disease Control and Prevention (CDC)', 'United States', 'https://www.cdc.gov/model-aquatic-health-code/media/pdfs/2023-mahc-508.pdf', 'Government', 'Public aquatic facilities (pools)', 'Model code language for public aquatic facilities; includes operational requirements affecting supervision and environment.', '', ''),
  ('water-polo-aquatic-sports-royal-life-saving-society-australia-guidelines-for--6a624c0f9711', 'Water polo / aquatic sports', 'Guidelines for Safe Pool Operation (GSPO) 2010 (PDF)', 'Royal Life Saving Society – Australia', 'Australia', 'https://www.royallifesaving.com.au/__data/assets/pdf_file/0020/41492/GSPO-2010.pdf', 'NGO', 'Aquatic facilities (pools)', 'Best-practice specifications and recommendations for safe pool design and operations.', '', ''),
  ('whitewater-tubing-u-s-national-park-service-river-and-stream-safety-https-www-2e4bf110c2c1', 'Whitewater tubing', 'River and Stream Safety', 'U.S. National Park Service', 'United States', 'https://www.nps.gov/articles/river-and-stream-safety.htm', 'Government', 'Rivers/streams (floating, swimming, general river recreation)', 'River and stream hazard awareness including currents, cold water, changing depths, and trip preparation.', '', ''),
  ('whitewater-tubing-u-s-national-park-service-river-safety-and-regulations-http-9cde836ca031', 'Whitewater tubing', 'River Safety and Regulations', 'U.S. National Park Service', 'United States', 'https://www.nps.gov/maca/planyourvisit/river-safety-and-regulations.htm', 'Government', 'River recreation (incl. floating)', 'River hazards and regulations; emphasizes dynamic conditions and safety equipment expectations.', '', ''),
  ('whitewater-tubing-american-whitewater-american-whitewater-safety-code-revised-2cff1de7639e', 'Whitewater tubing', 'American Whitewater Safety Code (Revised 2024) (PDF)', 'American Whitewater', 'United States', 'https://www.americanwhitewater.org/resources/repository/Safety%20Code%2024%20web%20Small.pdf', 'NGO', 'Whitewater river activities (paddling/river running)', 'Safety code addressing river hazards, rescue considerations, and preparation for moving-water environments.', '', ''),
  ('whitewater-tubing-american-canoe-association-aca-the-paddler-s-safety-checkli-71a43ce0bc32', 'Whitewater tubing', 'The Paddler’s Safety Checklist (PDF)', 'American Canoe Association (ACA)', 'United States', 'https://americancanoe.org/wp-content/uploads/documents/sei-educational_resources/paddlers_safety_checklist.pdf', 'NGO', 'Canoeing, kayaking, SUP, rafting', 'Checklist-style resource for trip planning, equipment, group preparedness, and risk awareness around rivers.', '', ''),
  ('whitewater-tubing-department-of-conservation-rafting-and-kayaking-river-safet-63867a9e6fc0', 'Whitewater tubing', 'Rafting and kayaking river safety', 'Department of Conservation', 'New Zealand', 'https://www.doc.govt.nz/parks-and-recreation/know-before-you-go/rafting-and-kayaking-river-safety/', 'Government', 'Rafting/kayaking river use (risk principles transferable to tubing)', 'Government guidance on river hazards and trip preparation for New Zealand rivers.', '', ''),
  ('whitewater-tubing-new-zealand-mountain-safety-council-nzmsc-river-safety-and--f10f5227cc29', 'Whitewater tubing', 'River Safety and How to Cross Safely', 'New Zealand Mountain Safety Council (NZMSC)', 'New Zealand', 'https://www.mountainsafety.org.nz/learn/skills/river-safety', 'NGO', 'River safety in outdoor trips', 'Resource on river hazard recognition and decision-making; includes cautions about unsafe conditions.', '', ''),
  ('whitewater-tubing-worksafe-new-zealand-adventure-activities-regulatory-inform-8b81e9fe2f65', 'Whitewater tubing', 'Adventure activities (regulatory information)', 'WorkSafe New Zealand', 'New Zealand', 'https://www.worksafe.govt.nz/topic-and-industry/adventure-activities/', 'Government', 'Commercial adventure activities (including water-based activities)', 'Regulatory overview for adventure activities, including requirements related to managing serious harm risks.', '', ''),
  ('whitewater-tubing-water-safety-new-zealand-water-safety-code-https-www-waters-0a36138c26fa', 'Whitewater tubing', 'Water Safety Code', 'Water Safety New Zealand', 'New Zealand', 'https://www.watersafetynz.org/staying-safe/water-safety-code', 'NGO', 'Water activities (general)', 'National water safety messaging framework addressing key behaviors and cautions around water.', '', ''),
  ('coastal-rock-pooling-intertidal-study-queensland-department-of-education-mari-bd421c324bfa', 'Coastal rock pooling / intertidal study', 'Marine organism activities (CARA Activity Guideline)', 'Queensland Department of Education', 'Australia (Queensland)', 'https://education.qld.gov.au/curriculum/stages-of-schooling/CARA/activity-guidelines/marine-organism-activities', 'Education', 'Intertidal/marine organism study activities', 'School activity guideline for intertidal/marine organism activities; hazards include tides, terrain, and supervision factors.', '', ''),
  ('coastal-rock-pooling-intertidal-study-u-s-national-park-service-tidepool-acti-4523a47960bc', 'Coastal rock pooling / intertidal study', 'Tidepool Activities', 'U.S. National Park Service', 'United States', 'https://www.nps.gov/olym/planyourvisit/tidepool-activities.htm', 'Government', 'Tidepool/intertidal visiting and programs', 'NPS guidance on tidepool etiquette and safety tips, including tide timing and site considerations.', '', ''),
  ('coastal-rock-pooling-intertidal-study-university-of-hawai-i-at-m-noa-intertid-02fbe5d6ecd0', 'Coastal rock pooling / intertidal study', 'Intertidal Field Trip How-To Guide (Cheat Sheet) (PDF)', 'University of Hawaiʻi at Mānoa', 'United States (Hawaiʻi)', 'https://manoa.hawaii.edu/exploringourfluidearth/sites/default/files/pd-forum-attachments/Intertidal%20Field%20Trip%20Cheat%20Sheet.pdf', 'Education', 'Intertidal field trips', 'Field trip planning sheet emphasizing tide planning, logistics, chaperones, and safety rules for intertidal sites.', '', ''),
  ('coastal-rock-pooling-intertidal-study-gov-uk-department-for-digital-culture-m-29e28737865a', 'Coastal rock pooling / intertidal study', 'Managing beach safety (downloadable guidance)', 'GOV.UK (Department for Digital, Culture, Media & Sport)', 'United Kingdom', 'https://www.gov.uk/government/publications/managing-beach-safety', 'Government', 'Beach and coastal site management', 'Government-hosted publication on managing beach safety, including hazards and control measures for coastal settings.', '', ''),
  ('coastal-rock-pooling-intertidal-study-hm-coastguard-coast-coastal-safety-info-cf44a800bee9', 'Coastal rock pooling / intertidal study', 'Coast: coastal safety information', 'HM Coastguard', 'United Kingdom', 'https://hmcoastguard.uk/coast', 'Government', 'Coastal activities (general)', 'Coastal hazard awareness and emergency actions relevant to tide-dependent shoreline environments.', '', ''),
  ('coastal-rock-pooling-intertidal-study-national-ocean-service-noaa-tide-tables-b181f8a2d5ba', 'Coastal rock pooling / intertidal study', 'Tide Tables', 'National Ocean Service (NOAA)', 'United States', 'https://tidesandcurrents.noaa.gov/tide_predictions.html', 'Government', 'Tides (planning for coastal access/exposure)', 'Official tide predictions used for planning tide-dependent shoreline access; supports timing and exposure awareness.', '', ''),
  ('coastal-rock-pooling-intertidal-study-department-of-conservation-abel-tasman--f129c8792e28', 'Coastal rock pooling / intertidal study', 'Abel Tasman Tide chart November 2026 - February 2027 (PDF)', 'Department of Conservation', 'New Zealand', 'https://www.doc.govt.nz/globalassets/documents/parks-and-recreation/tracks-and-walks/nelson-marlborough/tide-tables/november-2026-february-2027.pdf', 'Government', 'Tide-dependent access planning', 'Official low-water tide tables with explicit cautions about timing windows and environmental influences.', '', ''),
  ('coastal-rock-pooling-intertidal-study-scottish-wildlife-trust-investigate-roc-ca855d36ddad', 'Coastal rock pooling / intertidal study', 'Investigate rock pools: Educator notes (PDF)', 'Scottish Wildlife Trust', 'Scotland (United Kingdom)', 'https://scottishwildlifetrust.org.uk/wp-content/uploads/2024/04/Rockpools_educator_notes.pdf', 'NGO', 'Rockpooling/intertidal learning activities', 'Educator notes including activity planning considerations and site hazards for rock pool investigations.', '', ''),
  ('lake-swimming-non-beach-queensland-department-of-education-swimming-in-locati-5ed14cd4ad79', 'Lake swimming (non-beach)', 'Swimming in locations other than pools (CARA Activity Guideline)', 'Queensland Department of Education', 'Australia (Queensland)', 'https://education.qld.gov.au/curriculum/stages-of-schooling/CARA/activity-guidelines/swimming-in-locations-other-than-pools', 'Education', 'Open water swimming (lakes, rivers, beaches—non-pool settings)', 'School activity guideline addressing open water site selection, supervision, and environmental dependencies.', '', ''),
  ('lake-swimming-non-beach-royal-life-saving-society-australia-guidelines-for-in-f39012e81ac4', 'Lake swimming (non-beach)', 'Guidelines for Inland Waterway Safety', 'Royal Life Saving Society – Australia', 'Australia', 'https://www.royallifesaving.com.au/Aquatic-Risk-and-Guidelines/guidelines/guidelines-for-inland-waterway-safety', 'NGO', 'Inland waterways (lakes/rivers)', 'Guidelines for risk management at inland waterways; focuses on drowning/aquatic injury risk factors and controls.', '', ''),
  ('lake-swimming-non-beach-u-s-bureau-of-reclamation-swimming-safely-in-lakes-ri-d74d2a6f032b', 'Lake swimming (non-beach)', 'Swimming safely in lakes, rivers and streams (PDF)', 'U.S. Bureau of Reclamation', 'United States', 'https://www.usbr.gov/ssle/drowning_prevention/documents/SwimmingSafelyLakesRiversStreams.pdf', 'Government', 'Open water swimming in inland waters', 'Water safety resource focused on inland swimming hazards and supervision considerations.', '', ''),
  ('lake-swimming-non-beach-centers-for-disease-control-and-prevention-cdc-summer-eda3ca60e56b', 'Lake swimming (non-beach)', 'Summer Swim Safety', 'Centers for Disease Control and Prevention (CDC)', 'United States', 'https://www.cdc.gov/drowning/prevention/summer-swim-safety.html', 'Government', 'Swimming safety (general; includes open water)', 'Public health drowning-prevention guidance emphasizing supervision, lifejackets, and situational risks.', '', ''),
  ('lake-swimming-non-beach-royal-life-saving-society-uk-rlss-uk-open-water-safet-30589f1cec4c', 'Lake swimming (non-beach)', 'Open water safety tips', 'Royal Life Saving Society UK (RLSS UK)', 'United Kingdom', 'https://www.rlss.org.uk/open-water-safety-tips', 'NGO', 'Open water swimming', 'Open water safety considerations including environmental conditions and supervision/visibility cautions.', '', ''),
  ('lake-swimming-non-beach-royal-national-lifeboat-institution-rnli-open-water-s-3430ae64659d', 'Lake swimming (non-beach)', 'Open water swimming: safety advice', 'Royal National Lifeboat Institution (RNLI)', 'United Kingdom / Ireland', 'https://rnli.org/safety/choose-your-activity/open-water-swimming', 'NGO', 'Open water swimming (incl. inland and coastal)', 'Safety advice addressing cold water, conditions, visibility, and limitations of open water environments.', '', ''),
  ('lake-swimming-non-beach-water-safety-new-zealand-water-safety-code-https-www--f520edcf01f3', 'Lake swimming (non-beach)', 'Water Safety Code', 'Water Safety New Zealand', 'New Zealand', 'https://www.watersafetynz.org/staying-safe/water-safety-code', 'NGO', 'Water activities (general)', 'National water safety messaging framework for behaviors and cautions relevant to inland swimming contexts.', '', ''),
  ('lake-swimming-non-beach-surf-life-saving-new-zealand-open-water-swimming-wate-6bb2a3cd4988', 'Lake swimming (non-beach)', 'Open Water Swimming: water safety', 'Surf Life Saving New Zealand', 'New Zealand', 'https://www.surflifesaving.org.nz/water-safety/open-water-swimming', 'NGO', 'Open water swimming', 'Open water swimming safety messaging with emphasis on conditions, visibility, and supervision cautions.', '', ''),
  ('orienteering-navigation-queensland-department-of-education-orienteering-cara--5304a6b4e34c', 'Orienteering / navigation', 'Orienteering (CARA Activity Guideline)', 'Queensland Department of Education', 'Australia (Queensland)', 'https://education.qld.gov.au/curriculum/stages-of-schooling/CARA/activity-guidelines/orienteering', 'Education', 'Orienteering/navigation activities', 'School activity guideline covering supervision, participant competence, and context-dependent risks (terrain, remoteness).', '', ''),
  ('orienteering-navigation-british-orienteering-safety-guidelines-pdf-https-www--d7391df35aa6', 'Orienteering / navigation', 'Safety Guidelines (PDF)', 'British Orienteering', 'United Kingdom', 'https://www.britishorienteering.org.uk/images/uploaded/downloads/Safety_Guidelines.pdf', 'Governing Body', 'Orienteering', 'Governing body safety guidelines addressing participant safety management and event/activity considerations.', '', ''),
  ('orienteering-navigation-british-orienteering-coaching-safety-guidelines-pdf-h-54b13f6564a2', 'Orienteering / navigation', 'Coaching Safety Guidelines (PDF)', 'British Orienteering', 'United Kingdom', 'https://www.britishorienteering.org.uk/images/uploaded/downloads/Coaching_Safety_Guidelines.pdf', 'Governing Body', 'Orienteering coaching sessions', 'Coaching-focused safety guidance addressing supervision, environment, and participant management considerations.', '', ''),
  ('orienteering-navigation-international-orienteering-federation-iof-rules-https-b442def9132e', 'Orienteering / navigation', 'Rules', 'International Orienteering Federation (IOF)', 'International', 'https://orienteering.sport/iof/rules/', 'Governing Body', 'Orienteering (international rules framework)', 'International rules framework for orienteering disciplines, including competition environment and conduct requirements.', '', ''),
  ('orienteering-navigation-international-school-sport-federation-isf-orienteerin-66a5a5a073cf', 'Orienteering / navigation', 'Orienteering Technical Rules (PDF)', 'International School Sport Federation (ISF)', 'International', 'https://www.isfsports.org/wp-content/uploads/2024/09/OrienteeringTechnicalRules2024.pdf', 'Governing Body', 'School sport orienteering', 'Technical rules for school sport orienteering events, including event format and participation requirements.', '', ''),
  ('orienteering-navigation-the-outdoor-education-advisers-panel-oeap-guidance-do-16a3026c6f2d', 'Orienteering / navigation', 'Guidance Documents (National Guidance index)', 'The Outdoor Education Advisers'' Panel (OEAP)', 'United Kingdom', 'https://oeapng.info/guidance-documents/', 'Education', 'Educational visits and outdoor learning (incl. navigation-related activities)', 'Index to national guidance documents for off-site visits/outdoor learning, including good practice and supervision frameworks.', '', ''),
  ('orienteering-navigation-new-zealand-mountain-safety-council-nzmsc-navigation--c0c856fee5dc', 'Orienteering / navigation', 'Navigation: Learn the Basics', 'New Zealand Mountain Safety Council (NZMSC)', 'New Zealand', 'https://www.mountainsafety.org.nz/learn/skills/navigation', 'NGO', 'Navigation skills (maps/compass)', 'Navigation skills resource focusing on map/compass use and reducing the chance of getting lost in outdoor settings.', '', ''),
  ('orienteering-navigation-scouting-america-guide-to-safe-scouting-https-www-sco-bedeefdea656', 'Orienteering / navigation', 'Guide to Safe Scouting', 'Scouting America', 'United States', 'https://www.scouting.org/health-and-safety/gss/', 'NGO', 'Youth activities (incl. outdoor navigation contexts)', 'Safety guide for Scouting activities; includes supervision and risk management principles across outdoor programs.', '', '')
), dedup AS (
  SELECT DISTINCT ON (source_id) * FROM data ORDER BY source_id
), mapped AS (
  SELECT d.source_id, a.activity_id, d.activity_name, d.title, d.organization, d.jurisdiction, d.url, d.source_type, d.activities_covered_raw, d.brief_focus, d.authority_class, d.publication_date
  FROM dedup d
  JOIN "__ARP_SCHEMA__".activities a ON lower(a.activity_name) = lower(d.activity_name)
), affected AS (
  SELECT DISTINCT activity_id FROM mapped
), del_reports AS (
  DELETE FROM "__ARP_SCHEMA__".reports
  WHERE activity_id IN (SELECT activity_id FROM affected)
  RETURNING activity_id
), del_sources AS (
  DELETE FROM "__ARP_SCHEMA__".sources
  WHERE activity_id IN (SELECT activity_id FROM affected)
  RETURNING source_id
), upserted AS (
  INSERT INTO "__ARP_SCHEMA__".sources (source_id, activity_id, activity_name, title, organization, jurisdiction, url, source_type, activities_covered_raw, brief_focus, authority_class, publication_date)
  SELECT source_id, activity_id, activity_name, title, organization, jurisdiction, url, source_type, activities_covered_raw, brief_focus, authority_class, publication_date
  FROM mapped
  ON CONFLICT (source_id) DO UPDATE SET
    activity_id=EXCLUDED.activity_id,
    activity_name=EXCLUDED.activity_name,
    title=EXCLUDED.title,
    organization=EXCLUDED.organization,
    jurisdiction=EXCLUDED.jurisdiction,
    url=EXCLUDED.url,
    source_type=EXCLUDED.source_type,
    activities_covered_raw=EXCLUDED.activities_covered_raw,
    brief_focus=EXCLUDED.brief_focus,
    authority_class=EXCLUDED.authority_class,
    publication_date=EXCLUDED.publication_date
  RETURNING source_id
)
-- Ensure documents rows exist for all inserted/updated sources
INSERT INTO "__ARP_SCHEMA__".documents (source_id)
SELECT DISTINCT source_id FROM upserted
ON CONFLICT (source_id) DO NOTHING;
